### ISSUE TITLE
bug in the new one

### ISSUE THREAD

**Issue by windbender** [anvaka/kmins#3]
On line 52 of index.js:
   for (var i = 0; i < source.length/4; i += 4) {
If you take the total length of the image data and you step through in increments of 4, then you do not ALSO need to divide the length by four on the bounds check.  choose one of the two techniques. and ensure that your index math when pulling the pixels corresponds.  It would be slightly more performant to not multiply, so I would recommend using i < source.length  and i = i + 4  the would give you only additions load/save and bounds check within the loop. 

The effect of this is that you are only looking at the first 1/4 of your image data when you create your points. This would be, roughly, the top 1/4 of the images.

A good test of this would be to use an image which CLEARLY had clustering. For example a flag which has two or three horizontal stripes of different colors should cluster nicely.  However with this bug, the k-means system will have difficultly since most of the colors will be missing.

**Comment by anvaka** [comment]
Thank you for reporting this! I will get to the fix in the next episode of [the series](https://www.youtube.com/playlist?list=PLiyBhz6G0njKWPWETRtQzRnAJAvegVF9i). Probably in next couple weeks.

**Comment by anvaka** [comment]
> Probably in next couple weeks.

:) fixed today, didn't do the video.
